"""Dev/test SQLite state-store helpers for core foundation tables.

This package re-exports the full historical public API of the former
``personalos.state`` module (now split by domain across submodules), so
every existing ``from personalos.state import <name>`` or ``state.<name>``
call site keeps working unchanged.
"""

from __future__ import annotations

from personalos.state.routines import (
    ROUTINE_COMPLETION_TABLE,
    ROUTINE_STATUSES,
    ROUTINE_CADENCE_TYPES,
    ROUTINE_MISSED_BEHAVIOR_TYPES,
    list_routines,
    get_routine,
    count_routines,
    create_routine,
    update_routine_status_enabled,
    update_routine,
    get_routine_completion,
    list_routine_completions,
    count_routine_completions,
    record_routine_completion,
    validate_routine_status,
    validate_routine_enabled,
    validate_routine_cadence_type,
    validate_routine_missed_behavior,
)
from personalos.state.priorities_projects_followups import (
    PRIORITY_STATUSES,
    PROJECT_STATUSES,
    FOLLOWUP_STATUSES,
    list_priorities,
    get_priority,
    count_priorities,
    create_priority,
    update_priority,
    update_priority_status,
    get_project,
    create_project,
    get_followup,
    create_followup,
    validate_priority_status,
    validate_project_status,
    validate_followup_status,
    list_active_priorities,
    count_priorities_by_status,
    summarize_priorities,
    list_projects,
    count_projects,
    list_followups,
    count_followups,
)
from personalos.state.composer import (
    COMPOSER_STATE_TABLES,
    COMPOSER_PACKET_TYPES,
    COMPOSER_BRIEFING_WINDOWS,
    COMPOSER_PACKET_STATUSES,
    COMPOSER_OUTPUT_VALIDATION_STATUSES,
    COMPOSER_OUTPUT_STATUSES,
    MODEL_RUN_ROLES,
    MODEL_RUN_ADAPTERS,
    MODEL_RUN_STATUSES,
    validate_composer_packet_type,
    validate_composer_briefing_window,
    validate_composer_packet_status,
    validate_composer_output_validation_status,
    validate_composer_output_status,
    validate_model_run_role,
    validate_model_run_adapter,
    validate_model_run_status,
    create_composer_packet,
    get_composer_packet,
    update_composer_packet_status,
    list_composer_packets,
    count_composer_packets,
    create_composer_output,
    get_composer_output,
    list_composer_outputs,
    count_composer_outputs,
    create_model_run,
    get_model_run,
    list_model_runs,
    count_model_runs,
)
from personalos.state.synthesis_import import (
    SYNTHESIS_IMPORT_PREVIEW_TABLES,
    SYNTHESIS_IMPORT_SOURCE_TYPES,
    SYNTHESIS_IMPORT_INPUT_FORMATS,
    SYNTHESIS_IMPORT_PREVIEW_STATUSES,
    SYNTHESIS_IMPORT_RAW_EXCERPT_MAX_CHARS,
    validate_synthesis_import_source_type,
    validate_synthesis_import_input_format,
    validate_synthesis_import_preview_status,
    create_synthesis_import_preview,
    get_synthesis_import_preview,
    list_synthesis_import_previews,
    count_synthesis_import_previews,
    update_synthesis_import_preview_status,
)
from personalos.state.briefings import (
    BRIEFING_LOOP_STATE_TABLES,
    DAILY_PLAN_STATUSES,
    BRIEFING_OUTPUT_WINDOWS,
    BRIEFING_OUTPUT_DELIVERY_MODES,
    BRIEFING_OUTPUT_STATUSES,
    validate_daily_plan_status,
    validate_briefing_output_window,
    validate_briefing_output_delivery_mode,
    validate_briefing_output_status,
    create_daily_plan,
    get_daily_plan,
    update_daily_plan_status,
    list_daily_plans,
    count_daily_plans,
    create_briefing_output,
    get_briefing_output,
    list_briefing_outputs,
    count_briefing_outputs,
)
from personalos.state.reports import (
    REPORT_STATE_TABLES,
    REPORT_JOB_TYPES,
    REPORT_JOB_CADENCES,
    REPORT_JOB_STATUSES,
    REPORT_RUN_TYPES,
    REPORT_RUN_STATUSES,
    CHART_PACK_REVIEW_SOURCE_TYPES,
    CHART_PACK_REVIEW_STATUSES,
    validate_report_job_type,
    validate_report_job_cadence,
    validate_report_job_status,
    validate_report_run_type,
    validate_report_run_status,
    validate_chart_pack_review_source_type,
    validate_chart_pack_review_status,
    create_report_job,
    update_report_job,
    get_report_job,
    list_report_jobs,
    count_report_jobs,
    create_report_run,
    update_report_run,
    get_report_run,
    list_report_runs,
    count_report_runs,
    create_chart_pack_review,
    update_chart_pack_review,
    get_chart_pack_review,
    list_chart_pack_reviews,
    count_chart_pack_reviews,
)
from personalos.state.fitness import (
    FITNESS_STATE_TABLES,
    FITNESS_INTEGRATION_TYPES,
    FITNESS_INTEGRATION_STATUSES,
    FITNESS_VALIDATION_RUN_TYPES,
    FITNESS_VALIDATION_RUN_STATUSES,
    FITNESS_FILE_ROLES,
    FITNESS_FILE_CONTRACT_STATUSES,
    validate_fitness_integration_type,
    validate_fitness_integration_status,
    validate_fitness_validation_run_type,
    validate_fitness_validation_run_status,
    validate_fitness_file_role,
    validate_fitness_file_contract_status,
    create_fitness_integration_state,
    update_fitness_integration_state,
    get_fitness_integration_state,
    list_fitness_integration_states,
    count_fitness_integration_states,
    create_fitness_validation_run,
    update_fitness_validation_run,
    get_fitness_validation_run,
    list_fitness_validation_runs,
    count_fitness_validation_runs,
    create_fitness_file_contract,
    update_fitness_file_contract,
    get_fitness_file_contract,
    list_fitness_file_contracts,
    count_fitness_file_contracts,
)
from personalos.state.execution_rails_dev_state import (
    EXECUTION_RAIL_STATE_TABLES,
    build_todoist_task_record,
    create_todoist_task,
    get_todoist_task,
    get_todoist_task_by_dedupe_key,
    list_todoist_tasks,
    count_todoist_tasks,
    update_todoist_task_status,
    build_calendar_block_record,
    create_calendar_block,
    get_calendar_block,
    get_calendar_block_by_dedupe_key,
    list_calendar_blocks,
    count_calendar_blocks,
    update_calendar_block_status,
)
from personalos.state.permissions import (
    get_permission_setting,
    list_permission_settings,
    upsert_permission_setting,
)

CORE_STATE_TABLES = ("routines", "priorities", "projects", "followups")
COUNTABLE_STATE_TABLES = (
    CORE_STATE_TABLES
    + (ROUTINE_COMPLETION_TABLE,)
    + EXECUTION_RAIL_STATE_TABLES
    + COMPOSER_STATE_TABLES
    + SYNTHESIS_IMPORT_PREVIEW_TABLES
    + BRIEFING_LOOP_STATE_TABLES
    + REPORT_STATE_TABLES
    + FITNESS_STATE_TABLES
)

